resources:
  repositories:
    - repository: almtemplates
      type: git
      name: ALM/devops_pipelines
      ref: refs/tags/jsstack2.0.0

stages:
  - stage: continuous_integration
    jobs:
      - template: jsstack-pipeline/jsstack-pipeline.yml@almtemplates
        parameters:
          Portfolio: "ABC"
